# Generated by Django 4.1.2 on 2022-10-12 21:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_id_alter_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradername', models.CharField(max_length=200)),
                ('followers', models.IntegerField(blank=True, default=0, null=True)),
                ('profit', models.IntegerField(blank=True, default=0, null=True)),
                ('roi', models.IntegerField(blank=True, default=0, null=True)),
                ('profit_graph', models.ImageField(blank=True, default='assets/img/default.jpg', null=True, upload_to='')),
                ('cover_photo', models.ImageField(blank=True, default='assets/img/default.jpg', null=True, upload_to='')),
                ('drawdown', models.IntegerField(blank=True, default=0, null=True)),
                ('aum', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
