# Generated by Django 4.1.2 on 2022-10-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_trader_alter_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='aum_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='drawdown_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='roiprofit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='uppercent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
