# Generated by Django 4.1.2 on 2022-10-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_trader_aum_percent_trader_drawdown_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='profile_pic',
            field=models.ImageField(blank=True, default='assets/img/default.jpg', null=True, upload_to=''),
        ),
    ]
