# Generated by Django 4.1.2 on 2022-10-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
